### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by kwstat** [emorynlp/character-mining#3]
I don't think that Emory University has any legal authority to claim copyright on this text.  The text is copyright is already under a non-open copyright.

https://answers.yahoo.com/question/index?qid=20160707042107AAoHRUz&guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS91cmw_c2E9dCZyY3Q9aiZxPSZlc3JjPXMmc291cmNlPXdlYiZjZD0mdmVkPTJhaFVLRXdpSF91alo0c1hyQWhWT0hjMEtIVjhRQlRVUUZqQVFlZ1FJQ2hBQiZ1cmw9aHR0cHMlM0ElMkYlMkZhbnN3ZXJzLnlhaG9vLmNvbSUyRnF1ZXN0aW9uJTJGaW5kZXglM0ZxaWQlM0QyMDE2MDcwNzA0MjEwN0FBb0hSVXomdXNnPUFPdlZhdzBWb2lNeGdld2h4UXZmR2lGYzZTUWY&guce_referrer_sig=AQAAAMMnRth4yopxh6rYELY-EfLn2KZXp2Zq0-9aXcJAhcMVzpq3NtQ_mEwkICwz8Pt6m6qVC1KGd9w6ftvctHMQmywuBKDohpT95cR-_Q0NabYs-YDwn-FBvGHw8r01aAi0sLWKBHbLTgFI6o3e11ss9yRgG5QfyyQ3mI5HpoRV4uVO

**Comment by jdchoi77** [comment]
@kwstat we do not claim neither the copyright nor the authorship of the transcripts. It was clearly stated in our first paper that the transcripts are collected from fan sites such as http://www.livesinabox.com/friends/ or https://friends.fandom.com. However, we do have a right to claim the copyright of the annotation in the JSON files that we have put years of work and money into.

**Comment by kwstat** [comment]
Your license file https://github.com/emorynlp/character-mining/blob/master/LICENSE.txt currently claims copyright over the entire package. At a minimum, this file should be changed to clarify what copyright you claim (over JSON code) and what copyright you disown.  Beyond that, taking transcripts from fan sites does not in any way change the fact that the transcripts are copyrighted by Warner Bros.  Whether Warner Bros cares is a different question.

**Comment by jdchoi77** [comment]
@kwstat I have added the [NOTICE](https://github.com/emorynlp/character-mining/blob/master/NOTICE.txt) as recommended by Apache: https://infra.apache.org/apply-license.html

Thanks for brining this to our attention.
